# Generated by Django 2.0.4 on 2018-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesuser',
            name='user_id',
            field=models.CharField(default=-1, max_length=50, unique=True, verbose_name='персональный идентификатор'),
        ),
    ]
