# Generated by Django 2.0.4 on 2018-04-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description_short',
            field=models.CharField(blank=True, max_length=150, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, verbose_name='полное описание'),
        ),
    ]
