# Generated by Django 2.0.4 on 2018-04-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0002_auto_20180421_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description_short',
            field=models.CharField(blank=True, max_length=100, verbose_name='краткое описание'),
        ),
    ]
