# Generated by Django 2.0.4 on 2018-04-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0003_auto_20180422_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
